version: 2
jobs:
  build:
    machine: true
    resource_class: brianoh1979/server401
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
